import '../models/user_model.dart';
import '../models/room_model.dart';
import '../models/report_model.dart';
import '../models/notification_model.dart';

class MockDataService {
  static List<RumaUser> get mockUsers => [
        RumaUser(
          uid: 'civitas-001',
          email: 'mahasiswa@ruma.ac.id',
          name: 'Budi Santoso',
          nimNip: '21012345',
          role: UserRole.civitas,
          jurusan: 'Teknik Informatika',
          phone: '081234567890',
        ),
        RumaUser(
          uid: 'teknisi-001',
          email: 'teknisi@ruma.ac.id',
          name: 'Ahmad Rizki',
          nimNip: '19876543',
          role: UserRole.teknisi,
          phone: '081298765432',
        ),
        RumaUser(
          uid: 'admin-001',
          email: 'admin@ruma.ac.id',
          name: 'Dewi Lestari',
          nimNip: '19900101',
          role: UserRole.admin,
          phone: '081255553333',
        ),
      ];

  static List<Room> get mockRooms => [
        Room(
          id: 'room-001',
          name: 'Lab Komputer A',
          building: 'Gedung Rektorat',
          floor: 2,
          category: 'Laboratorium',
          healthScore: 92,
          activeIssues: 1,
          resolvedIssues: 15,
          qrCodeData: 'RUMA:room-001',
        ),
        Room(
          id: 'room-002',
          name: 'Ruang Kelas 301',
          building: 'Gedung Fakultas A',
          floor: 3,
          category: 'Kelas',
          healthScore: 78,
          activeIssues: 3,
          resolvedIssues: 22,
          qrCodeData: 'RUMA:room-002',
        ),
        Room(
          id: 'room-003',
          name: 'Perpustakaan Lantai 1',
          building: 'Gedung Perpustakaan',
          floor: 1,
          category: 'Perpustakaan',
          healthScore: 88,
          activeIssues: 0,
          resolvedIssues: 10,
          qrCodeData: 'RUMA:room-003',
        ),
        Room(
          id: 'room-004',
          name: 'Aula Serbaguna',
          building: 'Gedung Rektorat',
          floor: 1,
          category: 'Aula',
          healthScore: 65,
          activeIssues: 5,
          resolvedIssues: 8,
          qrCodeData: 'RUMA:room-004',
        ),
        Room(
          id: 'room-005',
          name: 'Lab Elektro',
          building: 'Gedung Fakultas B',
          floor: 2,
          category: 'Laboratorium',
          healthScore: 45,
          activeIssues: 7,
          resolvedIssues: 5,
          qrCodeData: 'RUMA:room-005',
        ),
        Room(
          id: 'room-006',
          name: 'Ruang Dosen A',
          building: 'Gedung Rektorat',
          floor: 3,
          category: 'Kantor',
          healthScore: 95,
          activeIssues: 0,
          resolvedIssues: 20,
          qrCodeData: 'RUMA:room-006',
        ),
      ];

  static List<Report> get mockReports => [
        Report(
          id: 'rpt-001',
          userId: 'civitas-001',
          userName: 'Budi Santoso',
          roomId: 'room-002',
          roomName: 'Ruang Kelas 301',
          category: 'AC',
          description: 'AC di ruang 301 tidak dingin, suhu mencapai 30 derajat.',
          priority: 'high',
          status: ReportStatus.inProgress,
          assignedTo: 'teknisi-001',
          assignedName: 'Ahmad Rizki',
          imageUrls: [],
        ),
        Report(
          id: 'rpt-002',
          userId: 'civitas-001',
          userName: 'Budi Santoso',
          roomId: 'room-004',
          roomName: 'Aula Serbaguna',
          category: 'Lampu',
          description: 'Lampu di panggung aula mati 2 buah.',
          priority: 'medium',
          status: ReportStatus.reported,
          imageUrls: [],
        ),
        Report(
          id: 'rpt-003',
          userId: 'civitas-001',
          userName: 'Budi Santoso',
          roomId: 'room-001',
          roomName: 'Lab Komputer A',
          category: 'Kebersihan',
          description:
              'LCD proyektor tidak fokus, perlu dibersihkan lensanya.',
          priority: 'low',
          status: ReportStatus.resolved,
          assignedTo: 'teknisi-001',
          assignedName: 'Ahmad Rizki',
          resolution: 'Lensa telah dibersihkan. Proyektor berfungsi normal.',
          imageUrls: [],
        ),
        Report(
          id: 'rpt-004',
          userId: 'civitas-001',
          userName: 'Budi Santoso',
          roomId: 'room-005',
          roomName: 'Lab Elektro',
          category: 'Listrik',
          description:
              'Stop kontak di meja 5 dan 6 tidak berfungsi. Tidak ada aliran listrik.',
          priority: 'high',
          status: ReportStatus.reported,
          imageUrls: [],
        ),
        Report(
          id: 'rpt-005',
          userId: 'civitas-001',
          userName: 'Budi Santoso',
          roomId: 'room-005',
          roomName: 'Lab Elektro',
          category: 'AC',
          description: 'AC mengeluarkan suara berisik dan tidak dingin.',
          priority: 'medium',
          status: ReportStatus.inProgress,
          assignedTo: 'teknisi-001',
          assignedName: 'Ahmad Rizki',
          imageUrls: [],
        ),
        Report(
          id: 'rpt-006',
          userId: 'civitas-001',
          userName: 'Budi Santoso',
          roomId: 'room-004',
          roomName: 'Aula Serbaguna',
          category: 'Meubelair',
          description: 'Kursi baris ke-3 ada yang patah kakinya.',
          priority: 'low',
          status: ReportStatus.rejected,
          resolution: 'Sudah dijadwalkan penggantian minggu depan.',
          imageUrls: [],
        ),
      ];

  static List<AppNotification> get mockNotifications => [
        AppNotification(
          id: 'notif-001',
          userId: 'civitas-001',
          title: 'Laporan Diproses',
          body: 'Laporan AC Ruang Kelas 301 sedang diproses oleh Teknisi.',
          type: 'report',
          reportId: 'rpt-001',
        ),
        AppNotification(
          id: 'notif-002',
          userId: 'civitas-001',
          title: 'Laporan Selesai',
          body: 'Laporan LCD Lab Komputer A telah selesai diperbaiki.',
          type: 'report',
          reportId: 'rpt-003',
          createdAt: DateTime.now().subtract(const Duration(days: 1)),
        ),
        AppNotification(
          id: 'notif-003',
          userId: 'civitas-001',
          title: 'Jadwal Maintenance',
          body: 'Gedung Rektorat akan dilakukan maintenance listrik besok pukul 09:00-12:00.',
          type: 'info',
          isRead: true,
          createdAt: DateTime.now().subtract(const Duration(days: 2)),
        ),
        AppNotification(
          id: 'notif-004',
          userId: 'civitas-001',
          title: 'Laporan Ditolak',
          body: 'Laporan kursi Aula Serbaguna ditolak. Sudah dijadwalkan penggantian.',
          type: 'report',
          reportId: 'rpt-006',
          createdAt: DateTime.now().subtract(const Duration(days: 3)),
        ),
        AppNotification(
          id: 'notif-005',
          userId: 'admin-001',
          title: 'Laporan Baru',
          body: 'Laporan baru dari Budi Santoso: Stop kontak Lab Elektro.',
          type: 'report',
          reportId: 'rpt-004',
        ),
      ];
}
