// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyyDysbc2XTRvNS9ydPhpy3OAytbM-POw',
    appId: '1:256881306554:web:04d4d0f36ee5b4d91ecb83',
    messagingSenderId: '256881306554',
    projectId: 'yogawahyu24',
    authDomain: 'yogawahyu24.firebaseapp.com',
    storageBucket: 'yogawahyu24.firebasestorage.app',
    measurementId: 'G-6HCNLNY4WH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaiuQ9B1PYlcgOrnmKhaQM3b8J_5Kb87I',
    appId: '1:256881306554:android:c1d6f0b34f02add71ecb83',
    messagingSenderId: '256881306554',
    projectId: 'yogawahyu24',
    storageBucket: 'yogawahyu24.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpm22lFEkI6DOzwWdFN7INKUUvnkWmoF4',
    appId: '1:256881306554:ios:31202e57326d74cd1ecb83',
    messagingSenderId: '256881306554',
    projectId: 'yogawahyu24',
    storageBucket: 'yogawahyu24.firebasestorage.app',
    iosBundleId: 'com.ruma.rumaApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpm22lFEkI6DOzwWdFN7INKUUvnkWmoF4',
    appId: '1:256881306554:ios:31202e57326d74cd1ecb83',
    messagingSenderId: '256881306554',
    projectId: 'yogawahyu24',
    storageBucket: 'yogawahyu24.firebasestorage.app',
    iosBundleId: 'com.ruma.rumaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyyDysbc2XTRvNS9ydPhpy3OAytbM-POw',
    appId: '1:256881306554:web:89944223628987841ecb83',
    messagingSenderId: '256881306554',
    projectId: 'yogawahyu24',
    authDomain: 'yogawahyu24.firebaseapp.com',
    storageBucket: 'yogawahyu24.firebasestorage.app',
    measurementId: 'G-91XVNGCL2Y',
  );
}
